version: "3.8"
services:
  spring:
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
    environment:
      MYSQL_URL: jdbc:mysql://mysqldb:3306/test-docker?createDatabaseIfNotExist=true
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
  mysqldb:
    platform: linux/x86_64
    image: "mysql:5.7"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: test-docker
      MYSQL_USER: test
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - db:/var/lib/mysql
volumes:
  db:

